---
title: "capscale and rda"
author: "Isabella"
date: "2025-07-17"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("devtools") ## this needs to be installed and loaded prior to running
### the following:
# install_github("helixcn/seqRFLP")
# install_github("JCSzamosi/aftersl1p@*release")

## load packages:
library("phyloseq")
library("ShortRead") 
library("tidyverse") ## ggplot, dplyr, et c.
library("Polychrome") ## generate randomized discrete colour palettes
library("paletteer") ## generate colour palettes
library("readr") ## read_csv function
library("cluster")
library("data.table")
library("grid")
library("ape")
library("phangorn")
library("phytools")
library("vegan")
library("seqinr")
library("seqRFLP")
library("AfterSl1p")
library("DESeq2")
library("patchwork")
library("tibble")
```

Bring in files
```{r}
otufile <- "C:/Users/Isabella/OneDrive/Desktop/16S_gh/seqtab_nochim_transposed_RD-Mar2025_v4.csv"

otu_df <- read.csv(otufile, row.names = 1)
seqs <- rownames(otu_df)
rownames(otu_df) = NULL
taxfile <- "C:/Users/Isabella/OneDrive/Desktop/16S_gh/taxa_RD-Mar2025_v4_silva1382WSP.csv"
tax_df <- read.csv(taxfile, row.names = 1)

all(seqs == rownames(tax_df))

rownames(tax_df) = NULL

metfile <- "C:/Users/Isabella/OneDrive/Desktop/16S_gh/mapfileV4.csv"
met_df <- read.csv(metfile)

```

Clean up metadata
```{r}
met_df$NAME <- factor(met_df$NAME, 
                      levels = c("RD1","RD2","RD3","RD4","RD5","RD6","RD7","RD8","RD9","RD10","RD11","RD12","RD13","RD14","RD15","RD16","RD17","RD18","RD19","RD20","RD21","RD22","RD23","RD24","RD25","RD26","RD27","RD28","RD29","RD30","RD31","RD32","RD33","RD34","RD35","RD36","RD37","RD38","RD39","RD40","RD41","RD42","RD43","RD44","RD45","RD46","RD47","RD48","RD49","RD50","RD51","RD52","RD53","RD54","RD55","RD56","RD57","RD58","RD59","RD60","RD61","RD62","RD63","RD64","RD65","RD66","RD67","RD68","RD69","RD70","RD71","RD72","RD73","RD74","RD75","RD76","RD77","RD78","RD79","RD80","RD81","RD82","RD83","RD84","RD85","RD86","RD87","RD88","RD89","RD90","RD91","RD92","RD93","RD94","RD95","RD96","RD97","RD98","RD99","RD100","RD101","RD102","RD103","RD104","RD105","RD106","RD107","RD108","RD109","RD110","RD111","RD112","RD113","RD114","RD115","RD116","RD117","RD118","RD119","RD120","RD121","RD122","RD123","RD124","RD125","RD126","RD127","RD128","RD129","RD130","RD131","RD132","RD133","RD134","RD135","RD136","RD137","RD138","RD139","RD140","RD141","RD142","RD143","RD144","RD145","RD146","RD147","RD148","RD149","RD150","RD151","RD152","RD153","RD154","RD155","RD156"))

rownames(met_df) <- met_df$NAME 

#checking that they match
rows <- sort(rownames(met_df))
cols <- sort(colnames(otu_df))
rows %in% cols #should all say TRUE
```
Making the phyloseq object. I determined how to rarefy for the microbiome data so I kept it the same here.
```{r}
ps <-  phyloseq(otu_table(otu_df, taxa_are_rows = TRUE), # or FALSE if false
               tax_table(as.matrix(tax_df)),
               sample_data(met_df))

dat_lessHOST <- subset_taxa(ps, Kingdom=="Bacteria", Family!="Mitochondria")

#remove less than 0.001%
rel_abun_all <- transform_sample_counts(dat_lessHOST, function(x) x/sum(x))
rel_abun_all_prune <- prune_taxa(taxa_sums(rel_abun_all) > 0.001,
                                rel_abun_all)

#rarefy, rarefying to 10000 based on curve
rare_ps <- rarefy_even_depth(dat_lessHOST,
                           sample.size=10000,
                           verbose=FALSE,
                           replace = FALSE)

#glom to family level, this function merges taxa based on their taxonomic rank, grouping into broader categories, was originally phylum, doesn't have to be this data aggregation step, Example, Imagine a phyloseq object with thousands of OTUs. Using tax_glom at the Genus level would merge all OTUs belonging to the same genus, resulting in a much smaller set of genus-level taxa.

rare_ps_family <- tax_glom(rare_ps, taxrank="Family")
```

Capscale with vegan function. Using Bray-Curtis. I also want to separate this by time point 1 and time point 2.
```{r}
T1 <- subset_samples(rare_ps_family, Sampling_date == "2024-07-11")
T2 <- subset_samples(rare_ps_family, Sampling_date %in% c("2024-08-18", "2024-08-06", "2024-08-19", "2024-08-26"))

cap_ord1 <- ordinate(
  physeq = T1,
  method = "CAP",
  distance = "bray",
  formula = ~ Treatment + Species + Treatment:Species
) #I kept formula the same as the model for the direct experiment

cap_ord2 <- ordinate(
  physeq = T2,
  method = "CAP",
  distance = "bray",
  formula = ~ Treatment + Species + Treatment:Species
)

T1_cap <- plot_ordination(T1, cap_ord1, type = "samples", color = "Treatment", shape = "Species")
T2_cap <- plot_ordination(T2, cap_ord2, type = "samples", color = "Treatment", shape = "Species")

T1_cap <- T1_cap + geom_point(aes(colour = Treatment, shape = Species), size = 4, alpha = 0.5) + ggtitle ("Bray-Curtis post harvest") + scale_colour_manual(values = c("gray", "chocolate3", "blue", "chocolate4", "navy", "chocolate1", "lightblue"), labels=c("Control", "Biosolid 1", "Reclaimed Water 1", "Biosolid 2", "Reclaimed Water 2", "Biosolid 0", "Reclaimed Water 0")) + theme_bw() + theme(plot.title=element_text(hjust = 0.5, size = 10), axis.title.x = element_text(size=10), axis.title.y = element_text(size=10), axis.text.x = element_text(size = 10), axis.text.y = element_text(size=10), legend.text = element_text(size = 10), legend.title = element_text(size =10)) + guides(shape=guide_legend(title = "Plant Species"), colour=guide_legend(title = "Past Treatment")) + scale_shape_discrete(labels=c("Lettuce", "Pea", "Radish"))

T2_cap <- T2_cap + geom_point(aes(colour = Treatment, shape = Species), size = 4, alpha = 0.5) + ggtitle ("Bray-Curtis post harvest") + scale_colour_manual(values = c("gray", "chocolate3", "blue", "chocolate4", "navy", "chocolate1", "lightblue"), labels=c("Control", "Biosolid 1", "Reclaimed Water 1", "Biosolid 2", "Reclaimed Water 2", "Biosolid 0", "Reclaimed Water 0")) + theme_bw() + theme(plot.title=element_text(hjust = 0.5, size = 10), axis.title.x = element_text(size=10), axis.title.y = element_text(size=10), axis.text.x = element_text(size = 10), axis.text.y = element_text(size=10), legend.text = element_text(size = 10), legend.title = element_text(size =10)) + guides(shape=guide_legend(title = "Plant Species"), colour=guide_legend(title = "Past Treatment")) + scale_shape_discrete(labels=c("Lettuce", "Pea", "Radish"))

T1_cap + T2_cap
```

Interpretation of capscale
```{r}
#Variance explained by the axes
summary(cap_ord1)
summary(cap_ord2)

#Significance testing of the variables
anova(cap_ord1, by = "term")
anova(cap_ord2, by = "term")
```

RDA
```{r}
rda_ord1 <- ordinate(
  physeq = T1,
  method = "RDA",
  distance = "bray",
  formula = ~ Treatment + Species + Treatment:Species
) 

rda_ord2 <- ordinate(
  physeq = T2,
  method = "RDA",
  distance = "bray",
  formula = ~ Treatment + Species + Treatment:Species
) 

T1_rda <- plot_ordination(T1, rda_ord1, type = "samples", color = "Treatment", shape = "Species")
T2_rda <- plot_ordination(T2, rda_ord2, type = "samples", color = "Treatment", shape = "Species")

T1_rda <- T1_rda + geom_point(aes(colour = Treatment, shape = Species), size = 4, alpha = 0.5) + ggtitle ("Bray-Curtis post harvest") + scale_colour_manual(values = c("gray", "chocolate3", "blue", "chocolate4", "navy", "chocolate1", "lightblue"), labels=c("Control", "Biosolid 1", "Reclaimed Water 1", "Biosolid 2", "Reclaimed Water 2", "Biosolid 0", "Reclaimed Water 0")) + theme_bw() + theme(plot.title=element_text(hjust = 0.5, size = 10), axis.title.x = element_text(size=10), axis.title.y = element_text(size=10), axis.text.x = element_text(size = 10), axis.text.y = element_text(size=10), legend.text = element_text(size = 10), legend.title = element_text(size =10)) + guides(shape=guide_legend(title = "Plant Species"), colour=guide_legend(title = "Past Treatment")) + scale_shape_discrete(labels=c("Lettuce", "Pea", "Radish"))

T2_rda <- T2_rda + geom_point(aes(colour = Treatment, shape = Species), size = 4, alpha = 0.5) + ggtitle ("Bray-Curtis post harvest") + scale_colour_manual(values = c("gray", "chocolate3", "blue", "chocolate4", "navy", "chocolate1", "lightblue"), labels=c("Control", "Biosolid 1", "Reclaimed Water 1", "Biosolid 2", "Reclaimed Water 2", "Biosolid 0", "Reclaimed Water 0")) + theme_bw() + theme(plot.title=element_text(hjust = 0.5, size = 10), axis.title.x = element_text(size=10), axis.title.y = element_text(size=10), axis.text.x = element_text(size = 10), axis.text.y = element_text(size=10), legend.text = element_text(size = 10), legend.title = element_text(size =10)) + guides(shape=guide_legend(title = "Plant Species"), colour=guide_legend(title = "Past Treatment")) + scale_shape_discrete(labels=c("Lettuce", "Pea", "Radish"))

T1_rda + T2_rda
```

Interpretation of RDA
```{r}
#Variance explained by the axes
summary(rda_ord1)
summary(rda_ord2)

#Significance testing of the variables
anova(rda_ord1, by = "term")
anova(rda_ord2, by = "term")

RsquareAdj(rda_ord1)
```


Kruskal Wallace Test
```{r}
#https://rpubs.com/lgschaerer/alphadiv

#alphadiv <- estimate_richness(T1, measures = c("Shannon")) %>% left_join(as.data.frame(sample_data(T1)))

```

